// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"XdRs_VirtualButtons","status":true,"description":"<MV + MZ> 虚拟按键","parameters":{"imgPath":"img/system/","opacity":"60","visible":"true","coexistTouch":"true","rockerX":"20","rockerY":"450","rockerDiam":"160","rockerFix":"true","rockerImg":"","seName":"","ballLimit":"true","ballImg":"","invalidScenes":"","keyA":"{\"x\":\"590\",\"y\":\"600\",\"width\":\"86\",\"height\":\"56\",\"value\":\"90\",\"text\":\"A\",\"img\":\"\",\"se\":\"\"}","keyB":"{\"x\":\"700\",\"y\":\"600\",\"width\":\"86\",\"height\":\"56\",\"value\":\"88\",\"text\":\"B\",\"img\":\"\",\"se\":\"\"}","keyC":"","keyD":"","keyE":"","==========================":"true"}}
];
