// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_ExternalLinks","status":true,"description":"v1.00 Link back to your home page through the title screen\nand also be able to link your players from within the game.","parameters":{"Home Page URL":"https://bblacg.com","Home Page Text":"巴比伦官网","Popup Blocker Notice":"The link was blocked by a pop-up blocker."}}
];
